name: Create Pull Request

on:
  push:
    branches: 
      -  main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3