name: Create Pull Request

on:
  push:
    branches: 
      -  main

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise Pull Request
        id: demo-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "qa_test_develop"
          base:  main
          title: "demo for auto pr version2"
          commiter: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"> 
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"> 
          body:
            This is to show automatic PR creation
          token:  ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_DEMO }}
          number: ${{ steps.demo-1.outputs.pull-request-number }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.demo-1.outputs.pull-request-number }}
          method: squash
